/** Zentrale Genre-Liste für Bücher und Einreichungen. Alphabetisch sortiert, "Sonstiges" am Ende. */
export const GENRE_OPTIONS = [
  "Abenteuer",
  "Biografie / Autobiografie",
  "Chick-Lit",
  "Comic / Manga / Graphic Novel",
  "Contemporary / Gegenwartsliteratur",
  "Cozy Mystery",
  "Dark Romance",
  "Detektivroman",
  "Drama",
  "Dystopie",
  "Erotik",
  "Fabel",
  "Familienroman",
  "Fantasy",
  "Fantasy – Dark Fantasy",
  "Fantasy – High Fantasy",
  "Fantasy – Urban Fantasy",
  "Gedichte / Lyrik",
  "Gesellschaftsroman",
  "Historischer Roman",
  "Horror",
  "Humor / Satire",
  "Jugendbuch (ab 12)",
  "Kinderbuch (ab 2)",
  "Kinderbuch (ab 6)",
  "Kinderbuch (ab 8)",
  "Klassiker",
  "Krimi",
  "Krimi / Thriller",
  "Kurzgeschichten",
  "LitRPG / GameLit",
  "Liebesroman / Romance",
  "Märchen / Sagen",
  "Mystery",
  "Naturführer / Bestimmungsbuch",
  "New Adult",
  "Philosophie",
  "Psychothriller",
  "Ratgeber / Selbsthilfe",
  "Reisebericht / Reiseführer",
  "Sachbuch",
  "Sachbuch – Geschichte",
  "Sachbuch – Naturwissenschaft",
  "Sachbuch – Politik / Gesellschaft",
  "Sachbuch – Psychologie",
  "Sachbuch – Sprache / Kultur",
  "Sachbuch – Technologie / IT",
  "Sachbuch – Wirtschaft / Finanzen",
  "Science-Fiction",
  "Science-Fiction – Cyberpunk",
  "Science-Fiction – Space Opera",
  "Spionageroman",
  "Steampunk",
  "Thriller",
  "True Crime",
  "Western",
  "Young Adult",
  "Sonstiges",
] as const;

export type Genre = (typeof GENRE_OPTIONS)[number];
